import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import ClientOnlyWrapper from "@/components/common/ClientOnlyWrapper";
import { AdminSidebar } from "@/components/common/AdminSidebar";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html
      lang="en"
      // className={inter.className}
    >
      <body>
        <div className="flex min-h-screen">
          <AdminSidebar />
          <main className="flex-1 bg-gray-50 p-6 overflow-y-auto">{children}</main>
        </div>
        <ClientOnlyWrapper />
      </body>
    </html>
  );
}
